name: Deploy PHP Project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Sync Files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: 'root'
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "."
          target: "/var/www/html/www.ipadpromanuals.com"
          strip_components: 1

      - name: Final Setup on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: 'root'
          password: ${{ secrets.SERVER_PASSWORD }}
          command_timeout: 90m
          script: |
            # Restart web server if needed
            sudo systemctl restart apache2
            # Remove .git and .github directories
            sudo rm -rf /var/www/html/www.ipadpromanuals.com/.git
            sudo rm -rf /var/www/html/www.ipadpromanuals.com/.github
